---
title: "Conclusion {#sec-chap6}"
author: "Alexandre Fortier-Chouinard"
bibliography: Thesis.bib
format: pdf
toc: true
toc-depth: 5
---
This dissertation started by asking one question: *How do men and women differ with regard to political interest, and why?* For the "how" question, boys and girls, and later women and men, tend to be interested in different political topics. These gender differences intersect with age: older women are particularly interested in the politics of education and health care, while younger men and boys tend to report high interest in partisan politics and international relations. For the *why* question, socialization by parents and peers has often been found to be the most important predictor of political interest in countries where norms about gender equality are more widely shared. This dissertation has clarified the role of parents and peers in children's political interest development: parents successfully transmit their political interests to their children who share their gender, while peers' role seems to be as important regardless of gender congruence.

## Contributions to the Scholarly Literature

What this dissertation makes clear is that developing interest in health care politics, law and crime, or another political topic, is not something that happens *solely* in the formative years of 15--25. Although interest in most of these topics does increase through adolescence, a general increase throughout adulthood can also be seen for all topics except partisan politics. Some later developments in life seem to be associated with the appearance of gender gaps in interest in health care and education politics, which only appear in the mid-30s. Women's and men's different experiences in caring for children and relatives, notably, remain different in countries like Canada and seem to be the most plausible explanations for the emergence of gender gaps in interest in health care and education.

This dissertation contributes to the literature on social learning theory. One of the implications of social learning theory is that children's attitudes and interests should be influenced by role models who share their gender. This assumption was tested among parents and confirmed for political interests more generally in @sec-chap4 --- although not individually for each of the topics tested. The assumption had, however, never been tested among friends. @sec-chap5 shows that friends' gender does not matter as much as parents' gender in predicting children's political interests. This result is surprising given that, as predicted by gender homophily theory, children overwhelmingly tend to stick with other children who share their gender. They also tend to discuss different topics depending on other children's gender, but this does not translate into higher political interest transmission of friends from one gender compared with friends of another gender.

The analysis presented here also contributes to the literature about political interest by clarifying, in the vein of recent studies by @campbellrosie2008 and @ferrin2020, that gender differences in political interest are not only about the *level* of political interest but also about the *type* of political interest. The level of political interest as well as the gender gaps vary between each of the five topics tested --- health care, international affairs, law and crime, education, and partisan politics. While all interest associations between topics are positive, most associations between interest in one political topic and interest in another topic are relatively weak among children and adults,^[The majority of correlation coefficients are under 0.4, moderately weak according to most scales [@akoglu2018]. See @fig-cordg and @fig-corccpis in @sec-appendix8.]. Canadians who are interested in the politics of health care may not be interested in international relations or partisan politics, and so on. Political interest can be divided into several components, and despite its close association with partisan politics, both measures remain different. The determinants of interest in each of the five topics would be worthy of future scientific investigation.

This dissertation also emphasizes gender differences in politics that do not have to do with ideology. Interest in a certain topic is not simply a measure of ideological support for extra government funding in that area --- if anything, the opposite might be true, as voters are more likely to start supporting increased funding after their awareness and interest in certain issues has been aroused. A recent study by @motta2019 finds that increased interest in science over time leads to more support for government funding of science, even after controlling for ideology, for instance. This research is therefore an invitation for more research about the determinants of political interests --- as these interests can lead to more discussion of various topics, something seen as desirable in participatory democracy.

For parents, what these findings suggest is that parental education matters. Political topics discussed at home have a significant influence over children's interests, and this is particularly the case for mother--daughter and father--son discussions. However, parents are only one source of socialization for children among many others. Other than parents and peers, two other socialization influences were tested in full models used in @sec-chap4 and @sec-chap5: teachers and social media influencers. These findings deserve further interest, given the importance of these two influences have sometimes been found to be as important as parents and peers [@oswald1998].

## Media

Tested alongside other influences, influencers' discussion of a specific topic is actually the strongest overall predictor of children's interest in that same topic in \ref{tab:lmeAgentsCtrl}. Other research about the role of media has generally found they play an important role in socialization.

An emerging literature has found influencers can increase youth political interest. @schmuck2022 hypothesize and show evidence that, among adolescents and young adults, political interest is negatively related to exposure to influencer content. Moreover, the relationship is stronger when there were interactions between influencer and follower in which the influencer engaged in perceived simplification of politics. @harff2022 similarly find among young women that interactions with an influencer increase the strength of the relationship between following an influencer and being interested in politics. @harff2024 find no relationship between adolescents and young adults' use of social media influencers as a *primary* source of political information and their level of political interest. Among older adults, @wasike2023 finds that following a social media influencer is positively related to political interest, which suggests it is possible that this type of influence can extend later in life.

With regards to media more generally, research has been done on the influence of political news on the development of political interest among adolescents. Although political interest can influence news media consumption, studies have shown the relationship also works in the other direction: watching more political news on traditional media and social media has a positive effect on political interest [@holt2013; @shehata2019]. Websites can also have a positive influence on people's political interest. @lupia2005 find young adults can gain political interest by visiting informative websites under certain conditions. More recently, @pap2018 find adolescents and young adults' political discussions on Facebook are related to their interest in politics, but not those on Twitter.

Given the emerging interest in the role of influencers in political socialization, it would be worth conducting a study to determine the extent to which transmission of political interests is easier when the influencer and follower share the same gender. A preliminary analysis in @sec-appendix9's Table \ref{tab:lmeInfluencer} shows few differences between the influence of same-gender influencers or other-gender influencers on political interests, although the coefficient for influencers who share the child's gender is larger (1.3 points agsinst 1.1 point). A closer examination of the role of influencers might be warranted.

## Schools

Tested alongside other influences, teachers' discussion of a specific topic is not significantly related to children's interest in that same topic in \ref{tab:lmeAgentsCtrl}. While teachers do not have a distinct influence on interest into particular topics in this study, the broader influence of schools on political interest development has been assessed time and again in various studies. Schools can influence childhood socialization in many ways, including citizenship education classes, classroom political discussions, extracurricular activities, and active learning strategies.

While earlier studies found only weak links between citizenship education classes and political interest [@langton1968], more recent studies find a positive link [@dassonneville2012; @maheo2019; @neundorf2016]. *Citizenship education* and *civic education* classes include classes teaching facts about government and politics but also promoting political engagement [@althof2006; @themistokleous2016].

Extracurricular and active learning activities can also affect youth political interest. The number of class group projects and membership in the school council are positively related to political interest, but not participation in voluntary associations nor parliamentary visits [@dassonneville2012].

Classroom political discussions in general can also increase students' political interest. For instance, students' perceptions of an *open classroom climate* marginally increase their political interest [@dassonneville2012], as well as several other aspects of their political engagement. An *open classroom climate* is one in which "students experience the discussion of social and political issues while in class and \[in which\] they feel comfortable contributing their own opinions during such discussions" [@campbell2007, p. 62].

The role of classroom political discussions in political socialization might be gendered. For instance, @mahony1985 finds that girls are less likely to participate in classroom discussions of politics because boys make the classroom climate aggressive. However, @rosenthal2003 show that, while girls' presence has a slightly positive impact on girls' speaking time, interruptions occur as frequently between adolescents whatever their gender and studies find that 8th- to 12th-grade girls are *more* likely than boys to report an open classroom climate [@blankenship1990; @campbell2007; @maurissen2018].^[Among adults, @karpowitz2014 and @beauvais2020 also show that women's and men's relative speaking time in a deliberative and decision-making setting depends on the number of women. When decisions are made by a majority, the presence of more women leads to more speaking time for each woman.]

Encouraging a variety of perspectives in political debates is something in participatory democracy [@collins2017; @phillips1992]. For political actors who seek a more gender-balanced set of political interests, having a variety of political topics spoken about in class may be a good way of getting different children's attention. Discussing health care politics and education politics in an open classroom climate could be a productive way for educators, organizations and political actors to foster long-lasting interest in health care and education politics. The extent to which the effects would be long-lasting may depend on several factors and would be worthy of future scientific inquiry. On the other hand, discussing partisan politics and international affairs in class may also increase girls' interest in these topics, since they tend to be less interested in that topic from a young age. In Quebec, these kinds of open classroom discussions about politics would be well-suited for classes such as the new *culture and Quebec citizenship* class (elementary and high school) as well as the *contemporary world* class (end of high school). In Ontario, they would be well-suited for grade 10 Civics classes but also for grades 1--6 Social Studies classes. More research about the extent to which this approach is currently used in Ontario and Quebec would be warranted.

With regards to interest in partisan politics, the fact that younger men report more interest may partly explain their overall higher intention to run for political office later in life. Discussing this topic more specifically in elementary school citizenship education classes could help even out girls and boys' interest in partisan politics and encourage young girls to see this as an option that is available to them when they reach adulthood. For scholars studying women's descriptive representation in politics, this link between interest in *partisan politics* specifically and political ambition would be a fruitful area where more studies could be conducted.

## Limitations

Some limitations about this dissertation are worth keeping in mind. Notably, age trends, especially in @sec-chap3, should be interpreted with caution. None of the data used is panel data, making it difficult to distinguish age effects from generational effects and life-cycle effects. While it is possible to say the gender gap in interest in health care seems to increase with age among adults, it is not possible to tell whether this is the result of older generations having a larger gender gap or whether similar patterns will happen when today's youth gets older.

Relatedly, CCPIS students from different age groups are not drawn in similar proportions from the same schools, and some schools only include classes from a certain age range, while others include students from several school years. Since schools may differ from each other on a variety of aspects, analyses comparing both age groups do not compare groups who are similar in every respect other than age. Comparisons of adults by age do not suffer from this issue since respondents are all drawn from the same pool.

More generally, CCPIS student data is a non-random, convenience sample. Its findings may not be generalizable to the broader population of Canadian adolescents or to adolescents worldwide. Representative samples of children and adolescents are difficult to access. These data remain an indication of what relationships may be in the broader population between the relevant variables, and there are no specific reasons to expect different correlations in the broader population. Percentages of girls, immigrants and ethnic minorities are broadly similar in the sample and general Canadian population of adolescents, despite geographic concentration in Ontario and --- mostly --- Quebec. Data analysis relying on the CES, WVS and GSS should be broadly representative of the Canadian population, especially after the use of survey weights, and the same goes for the Datagotchi PES and the Quebec population. Similar studies done elsewhere could provide further evidence about how important gender congruence is in the parental transmission of political interests in other contexts.

Finally, @stattin2022 suggest that personal political interest can influence perceptions of others' political interest or perceptions of the frequency of discussions with others. This study does not rely on panel data and cannot assess whether this is the case in Canada. However, authors rely on a single-item measure of political interest that may make the concept more blurry in children's minds than specifying specific political topics linked with even more specific political issues, as was done here. It seems unlikely that children's interest in diplomatic disputes between Canada and China would influence their perceptions of the frequency of their discussions with parents and peers about such disputes in the same way that general political interest could affect perceptions of the frequency of political discussions with adults. However, to formally test this hypothesis, future longitudinal studies should assess the causal influence of role models on children's political interests.

## Grammar Check