---
title: "Teachers, Influencers and Political Interest: School and Social Media as Other Venues of Acquisition"
author: "Alexandre Fortier-Chouinard"
bibliography: Thesis.bib
format: pdf
toc: true
toc-depth: 5
---
Gender homophily and social learning both suggest that children are influenced by same-gender models. These models include parents, as social learning theory finds it, and peers, as gender homophily theory finds it. However, it might be the case that other role models, including teachers and social media influencers, also have a broader influence on children of their gender. This would be coherent with the idea that observer-model similarity encourages children to model their behaviour on people who resemble them. Is gender homophily just one example among many of social learning through observer-model similarity?

manipulation?

"students who actively use social media have an increased level of support for conventional citizenship values and demonstrate more interest in active political participation in the future." [@blasko2019]

storytelling can be effective in increasing political engagement online [@vromen2022] (not sure for interest)

### Media

Research has been done on the influence of political news on the development of political interest among adolescents. Although political interest can influence news media consumption, studies have shown the relationship also works in the other direction: watching more political news on traditional media and on social media has a positive effect on political interest [@holt2013; @shehata2019].

Websites can also have a positive influence on people's political interest, although this literature might be somewhat old. @lupia2005 find young adults can gain political interest by visiting informative websites under certain conditions.

Studies mostly find boys use the Internet more frequently than girls. @willoughby2008 finds that boys use the Internet just as frequently as girls in early high school, but girls' Internet use decreases in late high school, notably due to a decline in gaming, making older teenage boys more active on the Internet than girls. @tsai2010 also find boys use the Internet more than girls in junior high school, but purpose-wise, girls use the Internet for communication while boys use it more for Web exploration.

Online political engagement is more prevalent among boys than girls according to @cicognani2012, but @livingstone2005 find that girls visit more political and civic websites.

### Schools

Schools can influence childhood socialization in many ways, including citizenship education classes, classroom political discussions, extracurricular activities, and active learning strategies.

While earlier studies found only weak links between citizenship education classes and political interest [@langton1968], more recent studies find a positive link [@dassonneville2012; @maheo2019; @neundorf2016]. *Citizenship education* and *civic education* classes include classes teaching facts about government and politics but also promoting political engagement [@althof2006; @themistokleous2016].

Extracurricular and active learning activities can affect youth political interest. The number of class group projects and membership in the school council are positively related to political interest, but not participation in voluntary associations nor parliamentary visits [@dassonneville2012].

Classroom political discussions in general can also increase students' political interest. For instance, students' perceptions of an *open classroom climate* marginally increase their political interest [@dassonneville2012]. An *open classroom climate* is one in which "students experience the discussion of social and political issues while in class and \[in which\] they feel comfortable contributing their own opinions during such discussions" [@campbell2007, p. 62].

The role of classroom political discussions in political socialization might be gendered. For instance, @mahony1985 finds that girls are less likely to participate in classroom discussions of politics because boys make the classroom climate aggressive. However, @rosenthal2003 show that, while girls' presence has a slightly positive impact on girls' speaking time, interruptions occur as frequently between adolescents whatever their gender, and studies find that 8th- to 12th-grade girls are *more* likely than boys to report an open classroom climate [@blankenship1990; @campbell2007; @maurissen2018].^[Among adults, @karpowitz2014 and @beauvais2020 also show that women's and men's relative speaking time in a deliberative and decision-making setting depends on the number of women. When decisions are made by a majority, the presence of more women leads to more speaking time for each woman.]

## References
