---
format: pdf
---
# CCPIS English Questionnaire {#sec-appendix1}

TITLE OF THE RESEARCH PROJECT: Gendered Political Socialization: Why Women and Men Still Differ on Political Interest

MAIN RESEARCHER: Alexandre Fortier-Chouinard, PhD student in political science at the University of Toronto

PROJECT BACKGROUND: PhD dissertation supervised by Professor Christopher Brian Cochrane

INFORMATION ON THE PROJECT: This research project aims to answer the following question: How do gender differences in interest in different political topics emerge?

YOUR PARTICIPATION: Your participation in this research consists in completing this questionnaire comprising 22 questions on political interest, on yourself and on your social network. Although answering each question is important for this research project, you are free to leave some or all questions unanswered or to terminate your participation at any time. Participation in this study will not be evaluated by your teacher. However, data obtained from a participant who chooses to withdraw from the project after submitting their questionnaire cannot be destroyed. One optional question will ask for your email address. If you decide to answer this question, which will only be used to contact you for optional follow-up surveys in 5 and 10 years, you can send me an email at `alexandre.fortier.chouinard@mail.utoronto.ca` to remove your email address from the list at any moment.

DATA CONSERVATION: The research ethics program may have confidential access to data to help ensure participant protection procedures are followed. The data from your answers will be destroyed in August 2037.

THANKS: Your collaboration is central to this study. Therefore, we would like to thank you for the time and attention you are willing to devote by participating.

CERTIFICATION OF CONSENT: Simply sending the completed online survey will be considered as an implied expression of your consent to participate in the project.

ADDITIONAL INFORMATION: If you have questions about the research or the implications of your participation, please contact Alexandre Fortier-Chouinard (email: `alexandre.fortier.chouinard@mail.utoronto.ca`) or the project's faculty supervisor, Prof. Christopher Brian Cochrane (email: `christopher.cochrane@utoronto.ca`). If you have questions about your rights as research participants, you can also contact the University of Toronto's office of research ethics (`ethics.review@utoronto.ca`, 416-946-3273). We are taking all safety precautions to reduce the risk of spread of COVID-19.

    - I accept to participate in this survey
    - I do not accept to participate in this survey

0. What 8-digit number have you been assigned?

1. When you think about politics, what kinds of things come to your mind? What does politics mean for you?
    - (Open field)

2. How interested are you in politics generally? Set the slider to a number from 0 to 10, where 0 means no interest at all, and 10 means a great deal of interest.
    - (0--10 slider)
    - Don't know/Prefer not to answer

3. Among the following topics, please indicate which ones you think are political and which you think are not political.

    + 3.1 Pandemic restrictions
        - Political
        - Not political
        - Don't know/Prefer not to answer

    + 3.2 Working conditions of nurses
        - Political
        - Not political
        - Don't know/Prefer not to answer

    + 3.3 Diplomatic disputes between Canada and China
        - Political
        - Not political
        - Don't know/Prefer not to answer

    + 3.4 Ukrainian war
        - Political
        - Not political
        - Don't know/Prefer not to answer

    + 3.5 Police funding
        - Political
        - Not political
        - Don't know/Prefer not to answer

    + 3.6 Sentences for violent crimes
        - Political
        - Not political
        - Don't know/Prefer not to answer
      
    + 3.7 University tuition
        - Political
        - Not political
        - Don't know/Prefer not to answer
      
    + 3.8 Funding of public and private schools
        - Political
        - Not political
        - Don't know/Prefer not to answer
      
    + 3.9 Federal elections
        - Political
        - Not political
        - Don't know/Prefer not to answer
      
    + 3.10 Political parties
        - Political
        - Not political
        - Don't know/Prefer not to answer

4. If you were to open a news website and see the following articles how interested would you be in reading each article? Set the slider to a number from 0 to 10, where 0 means "Not at all interested, I would not read it," and 10 means "Very interested, I would most likely read it."

    + 4.1 Health care (i.e., pandemic restrictions, working conditions of nurses)
        - (0--10 slider)
        - Don't know/Prefer not to answer

    + 4.2 International affairs (i.e., diplomatic disputes between Canada and China, Ukrainian war)
        - (0--10 slider)
        - Don't know/Prefer not to answer

    + 4.3 Law and crime (i.e., police funding, sentences for violent crimes)
        - (0--10 slider)
        - Don't know/Prefer not to answer

    + 4.4 Education (i.e., university tuition, funding of public and private schools)
        - (0--10 slider)
        - Don't know/Prefer not to answer

    + 4.5 Partisan politics (i.e., federal elections, political parties)
        - (0--10 slider)
        - Don't know/Prefer not to answer

5. Which of the following best describes your family situation, regardless of whether your biological parents live together or not?
  - One mother, one father and no stepparents
  - One mother, one father and at least one stepparent
  - One mother only [skip questions 6, 7 and 9]
  - One father only [skip questions 6--8]
  - Two mothers [skip questions 6, 7 and 9]
  - Two fathers [skip questions 6--8]
  - Other [skip questions 6--9]

6. Which parent do you discuss most often with?
  - Mother
  - Father
  - Both equally
  - Don't know/Prefer not to answer

7. For each of the following topics, which parent do you discuss most often with?

    + 7.1 Health care
        - My mother
        - My father
        - Don't know/Prefer not to answer

    + 7.2 International affairs
        - My mother
        - My father
        - Don't know/Prefer not to answer

    + 7.3 Law and crime
        - My mother
        - My father
        - Don't know/Prefer not to answer

    + 7.4 Education
        - My mother
        - My father
        - Don't know/Prefer not to answer

    + 7.5 Partisan politics
        - My mother
        - My father
        - Don't know/Prefer not to answer

8. Among these five topics, which one do you discuss most often with your mother(s)?
  - Health care
  - International affairs
  - Law and crime
  - Education
  - Partisan politics
  - Don't know/Prefer not to answer

9. Among these five topics, which one do you discuss most often with your father(s)?
  - Health care
  - International affairs
  - Law and crime
  - Education
  - Partisan politics
  - Don't know/Prefer not to answer

10. What is the gender of most of your friends?
  - Girls
  - Boys
  - About the same for both genders
  - Don't know/Prefer not to answer

11. Among these five topics, which one do you discuss most often with your male friends?
  - Health care
  - International affairs
  - Law and crime
  - Education
  - Partisan politics
  - Don't know/Prefer not to answer

12. Among these five topics, which one do you discuss most often with your female friends?
  - Health care
  - International affairs
  - Law and crime
  - Education
  - Partisan politics
  - Don't know/Prefer not to answer

13. Think about a teacher that you like(d).

    + 13.1 Among these five topics, which one is (was) mentioned most often by this teacher?
        - Health care
        - International affairs
        - Law and crime
        - Education
        - Partisan politics
        - Don't know/Prefer not to answer

    + 13.2 Is that teacher...
        - A woman
        - A man
        - Other (e.g. Trans, non-binary, two-spirit, gender-queer)

14. Think about someone that you like and sometimes read or watch on social media --- including YouTube.

    + 14.1 Among these five topics, which one is mentioned most often by this person?
        - Health care
        - International affairs
        - Law and crime
        - Education
        - Partisan politics
        - Don't know/Prefer not to answer

    + 14.2 Is that person...
        - A man
        - A woman
        - Other (e.g. Trans, non-binary, two-spirit, gender-queer)

15. Are you...
  - A girl
  - A boy
  - Other (e.g. Trans, non-binary, two-spirit, gender-queer)

16. In what year were you born?
  - (All years from 1990 to 2021)

17. Which language do you usually speak at home?
  - English
  - French
  - Aboriginal language (please specify ____)
  - Arabic
  - Chinese, Cantonese, Mandarin
  - Filipino / Tagalog
  - German
  - Indian, Hindi, Gujarati
  - Italian
  - Korean
  - Pakistani, Punjabi, Urdu
  - Persian, Farsi
  - Russian
  - Spanish
  - Tamil
  - Vietnamese
  - Other (please specify ____)
  - Don't know/Prefer not to answer

18. Are you...
  - First Nations (North American Indian), Métis or Inuk (Inuit)
  - White
  - South Asian (e.g., East Indian, Pakistani, Sri Lankan, etc.)
  - Chinese
  - Black
  - Filipino
  - Latin American
  - Arab
  - Southeast Asian (e.g., Vietnamese, Cambodian, Laotian, Thai, etc.)
  - West Asian (e.g., Iranian, Afghan, etc.)
  - Korean
  - Japanese
  - Other (please specify ____)
  - Don't know/Prefer not to answer

19. Were you born in Canada?
  - Yes
  - No
  - Don't know/Prefer not to answer

20. For each of these pairs of characteristics, indicate where you fall on a scale between both extremes.

    + 20.1 Not at all independent - Very independent
        - (1--5 slider)
        - Don't know/Prefer not to answer
      
    + 20.2 Very passive - Very active
        - (1--5 slider)
        - Don't know/Prefer not to answer
      
    + 20.3 Not at all competitive - Very competitive
        - (1--5 slider)
        - Don't know/Prefer not to answer
      
    + 20.4 Can make decisions easily - Have difficulty making decisions
        - (1--5 slider)
        - Don't know/Prefer not to answer
      
    + 20.5 Give up very easily - Never give up easily
        - (1--5 slider)
        - Don't know/Prefer not to answer
      
    + 20.6 Not at all self-confident - Very self confident
        - (1--5 slider)
        - Don't know/Prefer not to answer
      
    + 20.7 Feel very inferior - Feel very superior
        - (1--5 slider)
        - Don't know/Prefer not to answer
      
    + 20.8 Go to pieces under pressure - Stand up well under pressure
        - (1--5 slider)
        - Don't know/Prefer not to answer
      
    + 20.9 Not at all emotional - Very emotional
        - (1--5 slider)
        - Don't know/Prefer not to answer
      
    + 20.10 Not at all able to devote self to others - Able to devote self completely to others
        - (1--5 slider)
        - Don't know/Prefer not to answer
      
    + 20.11 Very rough - Very gentle
        - (1--5 slider)
        - Don't know/Prefer not to answer
      
    + 20.12 Not at all helpful to others - Very helpful to others
        - (1--5 slider)
        - Don't know/Prefer not to answer
      
    + 20.13 Not at all kind - Very kind
        - (1--5 slider)
        - Don't know/Prefer not to answer
      
    + 20.14 Not at all aware of feelings of others - Very aware of feelings of others
        - (1--5 slider)
        - Don't know/Prefer not to answer
      
    + 20.15 Not at all understanding of others - Very understanding of others
        - (1--5 slider)
        - Don't know/Prefer not to answer
      
    + 20.16 Very cold in relations with others - Very warm in relations with others
        - (1--5 slider)
        - Don't know/Prefer not to answer

21. We might do a follow-up survey in a few years. If you accept to be contacted by email for this survey, what is your current email address? Leave the field blank if you do not wish to be recontacted for this.
  - (Open field)

# CCPIS French Questionnaire {#sec-appendix2}

TITRE DE LA RECHERCHE : Socialisation politique genrée : Pourquoi les femmes et les hommes diffèrent encore en matière d'intérêt politique

CHERCHEUR PRINCIPAL : Alexandre Fortier-Chouinard, étudiant au doctorat en science politique à l'University of Toronto

CONTEXTE DU PROJET : Thèse de doctorat dirigée le professeur Christopher Brian Cochrane

RENSEIGNEMENTS SUR LE PROJET : Ma thèse vise à répondre à la question suivante : Comment émergent les différences de genre dans l'intérêt pour différents sujets politiques?

VOTRE PARTICIPATION : Votre participation à cette recherche consistera à remplir le présent questionnaire comprenant 22 questions portant sur l'intérêt politique, sur vous-mêmes et sur votre entourage. Bien que les réponses à chacune des questions soient importantes pour la recherche, vous demeurez libre de choisir de ne pas répondre à l’une ou l’autre d’entre elles ou encore de mettre fin à votre participation à tout moment. La participation à cette étude ne sera pas évaluée par votre enseignant. Toutefois, les données obtenues d’un(e) participant(e) qui choisirait de se retirer du projet après avoir soumis son questionnaire ne pourront être détruites. Une question facultative vous demandera votre adresse courriel. Si vous décidez de répondre à cette question, qui sera seulement utilisée pour vous contacter pour des sondages de suivi facultatifs dans 5 et 10 ans, vous pouvez m'envoyer un courriel à `alexandre.fortier.chouinard@mail.utoronto.ca` pour retirer votre adresse courriel de la liste à n'importe quel moment. Une question vous demandera votre numéro d'élève. Nous ne pouvons pas lier cette information avec aucune information personnelle au sujet de l'élève, incluant son nom, et cette information peut seulement être utilisée pour lier des questionnaires soumis à différents moments dans le temps par le même élève.

CONSERVATION DES DONNÉES : Le programme d'éthique de la recherche peut avoir un accès confidentiel aux données pour aider à garantir le respect des procédures de protection des participants. Les données issues de vos réponses seront détruites en août 2037.

REMERCIEMENTS : Votre collaboration est précieuse pour nous permettre de réaliser cette étude. C’est pourquoi nous tenons à vous remercier pour le temps et l’attention que vous acceptez de consacrer à votre participation.

ATTESTATION DU CONSENTEMENT : Le simple retour du sondage en ligne rempli sera considéré comme l’expression implicite de votre consentement à participer au projet.

RENSEIGNEMENTS SUPPLÉMENTAIRES: Si vous avez des questions sur la recherche ou sur les implications de votre participation, veuillez communiquer avec Alexandre Fortier-Chouinard (courriel : `alexandre.fortier.chouinard@mail.utoronto.ca`) ou le superviseur du projet, le professeur Christopher Brian Cochrane (courriel : `christopher.cochrane@utoronto.ca`). Si vous avez des questions sur vos droits en tant que participant(e) à la recherche, vous pouvez également contacter le bureau d'éthique de la recherche de l'University of Toronto (`ethics.review@utoronto.ca`, 416-946-3273). Nous prenons toutes les précautions de sécurité pour réduire le risque de propagation de la COVID-19.

    - J'accepte de participer à cette recherche
    - Je n'accepte pas de participer à cette recherche

0 Quel numéro à 8 chiffres t'a-t-on attribué?

1. Quand tu penses à la politique, quelles sont les choses qui te viennent à l'esprit? Que signifie la politique pour toi?
    - (Champ libre)

2. Quel est ton intérêt pour la politique en général? Glisse la barre sur un chiffre de 0 à 10, où 0 indique aucun intérêt du tout et 10 indique beaucoup d'intérêt.
    - (barre de 0--10)
    - Je ne sais pas/Préfère ne pas répondre

3. Parmi les sujets suivants, indique ceux qui, selon toi, sont politiques et ceux qui ne le sont pas.

    + 3.1 Restrictions en cas de pandémie
        - Politique
        - Pas politique
        - Je ne sais pas/Préfère ne pas répondre

    + 3.2 Conditions de travail des infirmiers(ères)
        - Politique
        - Pas politique
        - Je ne sais pas/Préfère ne pas répondre

    + 3.3 Conflits diplomatiques entre le Canada et la Chine
        - Politique
        - Pas politique
        - Je ne sais pas/Préfère ne pas répondre

    + 3.4 Guerre en Ukraine
        - Politique
        - Pas politique
        - Je ne sais pas/Préfère ne pas répondre

    + 3.5 Financement de la police
        - Politique
        - Pas politique
        - Je ne sais pas/Préfère ne pas répondre

    + 3.6 Peines pour des crimes violents
        - Politique
        - Pas politique
        - Je ne sais pas/Préfère ne pas répondre
      
    + 3.7 Frais de scolarité universitaires
        - Politique
        - Pas politique
        - Je ne sais pas/Préfère ne pas répondre
      
    + 3.8 Financement des écoles publiques et privées
        - Politique
        - Pas politique
        - Je ne sais pas/Préfère ne pas répondre
      
    + 3.9 Élections fédérales
        - Politique
        - Pas politique
        - Je ne sais pas/Préfère ne pas répondre
      
    + 3.10 Partis politiques
        - Politique
        - Pas politique
        - Je ne sais pas/Préfère ne pas répondre

4. Si tu ouvrais un site Web d'information et que tu voyais les articles suivants, dans quelle mesure serais-tu intéressé par la lecture de chaque article? Déplace la barre vis-à-vis un nombre compris entre 0 et 10, où 0 signifie <<&nbsp;Pas du tout intéressé, je ne le lirai pas&nbsp;>> et 10 signifie <<&nbsp;Très intéressé, je le lirai très probablement&nbsp;>>.

    + 4.1 Santé (ex.: restrictions en cas de pandémie, conditions de travail des infirmiers(ères))
        - (barre de 0--10)
        - Je ne sais pas/Préfère ne pas répondre

    + 4.2 Affaires internationales (ex.: conflits diplomatiques entre le Canada et la Chine, guerre en Ukraine)
        - (barre de 0--10)
        - Je ne sais pas/Préfère ne pas répondre

    + 4.3 Loi et crime (ex.: financement de la police, peines pour des crimes violents)
        - (barre de 0--10)
        - Je ne sais pas/Préfère ne pas répondre

    + 4.4 Éducation (ex.: frais de scolarité universitaires, financement des écoles publiques et privées)
        - (barre de 0--10)
        - Je ne sais pas/Préfère ne pas répondre

    + 4.5 Politique partisane (ex.: élections fédérales, partis politiques)
        - (barre de 0--10)
        - Je ne sais pas/Préfère ne pas répondre

5. Lequel des choix suivants décrit le mieux ta situation familiale, peu importe que tes parents biologiques vivent ensemble ou non?
  - Une mère, un père et aucun beau-parent
  - Une mère, un père et au moins un beau-parent
  - Une mère uniquement [sauter les questions 6, 7 et 9]
  - Un père uniquement [sauter les questions 6--8]
  - Deux mères [sauter les questions 6, 7 et 9]
  - Deux pères [sauter les questions 6--8]
  - Autre [sauter les questions 6--9]

6. Avec quel parent discutes-tu le plus souvent?
  - Ma mère
  - Mon père
  - Les deux autant
  - Je ne sais pas/Préfère ne pas répondre

7. Pour chacun des sujets suivants, avec quel parent discutes-tu le plus souvent?

    + 7.1 Santé
        - Ma mère
        - Mon père
        - Je ne sais pas/Préfère ne pas répondre

    + 7.2 Affaires internationales
        - Ma mère
        - Mon père
        - Je ne sais pas/Préfère ne pas répondre

    + 7.3 Loi et crime
        - Ma mère
        - Mon père
        - Je ne sais pas/Préfère ne pas répondre

    + 7.4 Éducation
        - Ma mère
        - Mon père
        - Je ne sais pas/Préfère ne pas répondre

    + 7.5 Politique partisane
        - Ma mère
        - Mon père
        - Je ne sais pas/Préfère ne pas répondre

8. Parmi ces cinq sujets, lequel discutes-tu le plus souvent avec ta mère (tes mères)?
  - Santé
  - Affaires internationales
  - Loi et crime
  - Éducation
  - Politique partisane
  - Je ne sais pas/Préfère ne pas répondre

9. Parmi ces cinq sujets, lequel discutes-tu le plus souvent avec ton père (tes pères)?
  - Santé
  - Affaires internationales
  - Loi et crime
  - Éducation
  - Politique partisane
  - Je ne sais pas/Préfère ne pas répondre

10. Quel est le genre de la plupart de tes amis?
  - Filles
  - Garçons
  - Environ autant des deux genres
  - Je ne sais pas/Préfère ne pas répondre

11. Parmi ces cinq sujets, lequel discutes-tu le plus souvent avec tes amis garçons?
  - Santé
  - Affaires internationales
  - Loi et crime
  - Éducation
  - Politique partisane
  - Je ne sais pas/Préfère ne pas répondre

12. Parmi ces cinq sujets, lequel discutes-tu le plus souvent avec tes amies filles?
  - Santé
  - Affaires internationales
  - Loi et crime
  - Éducation
  - Politique partisane
  - Je ne sais pas/Préfère ne pas répondre

13. Pense à un(e) enseignant(e) que tu apprécies (ou as apprécié).

    + 13.1 Parmi ces cinq sujets, lequel est (était) mentionné le plus souvent par cet(te) enseignant(e)?
        - Santé
        - Affaires internationales
        - Loi et crime
        - Éducation
        - Politique partisane
        - Je ne sais pas/Préfère ne pas répondre

    + 13.2 Cet enseignant(e) est-il(elle)...
        - Une femme
        - Un homme
        - Autre (ex.: trans, non-binaire, bispirituel, gender-queer)

14. Pense à une personne que tu apprécies et que tu lis ou regardes parfois sur les médias sociaux --- y compris YouTube.

    + 14.1 Parmi ces cinq sujets, lequel est mentionné le plus souvent par cette personne?
        - Santé
        - Affaires internationales
        - Loi et crime
        - Éducation
        - Politique partisane
        - Je ne sais pas/Préfère ne pas répondre

    + 14.2 Cette personne est-elle...
        - Une femme
        - Un homme
        - Autre (ex.: trans, non-binaire, bispirituel, gender-queer)

15. Es-tu...
  - Une fille
  - Un garçon
  - Autre (ex.: trans, non-binaire, bispirituel, gender-queer)

16. En quelle année es-tu né(e)?
  - (Toutes les années entre 1990 et 2021)

17. Quelle langue parles-tu à la maison d'habitude?
  - Anglais
  - Français
  - Langue autochtone (veuillez préciser ____)
  - Arabe
  - Chinois, cantonais, mandarin
  - Philippin / tagalog
  - Allemand
  - Indien, Hindi, Gujarati
  - Italien
  - Coréen
  - Pakistanais, Pendjabi, Ourdou
  - Persan, farsi
  - Russe
  - Espagnol
  - Tamil
  - Vietnamien
  - Autre (veuillez spécifier ____)
  - Je ne sais pas/Préfère ne pas répondre

18. Es-tu...
  - Première Nation (Indien(ne) de l'Amérique du Nord), Métis(se) ou Inuk (Inuit)
  - Blanc(he)
  - Sud-Asiatique (ex.: Indien(ne) de l'Inde, Pakistanais(e), Sri-Lankais(e), etc.)
  - Chinois(e)
  - Noir(e)
  - Philippin(e)
  - Latino-Américain(e)
  - Arabe
  - Asiatique du Sud-Est (ex.: Vietnamien(ne), Cambodgien(ne), Laotien(ne), Thaïlandais(e), etc.)
  - Asiatique occidental(e) (e.g., Iranien(ne), Afghan(e), etc.)
  - Coréen(ne)
  - Japonais(e)
  - Autre (veuillez spécifier ____)
  - Je ne sais pas/Préfère ne pas répondre

19. Es-tu né(e) au Canada?
  - Oui
  - Non
  - Je ne sais pas/Préfère ne pas répondre

20. Pour chacune de ces paires de caractéristiques, indique où tu te situes sur une échelle entre les deux extrêmes.

    + 20.1 Pas du tout indépendant(e) - Très indépendant(e)
        - (barre de 1--5)
        - Je ne sais pas/Préfère ne pas répondre
      
    + 20.2 Très passif(ive) - Très actif(ive)
        - (barre de 1--5)
        - Je ne sais pas/Préfère ne pas répondre
      
    + 20.3 Pas du tout compétitif(ive) - Très compétitif(ive)
        - (barre de 1--5)
        - Je ne sais pas/Préfère ne pas répondre
      
    + 20.4 Peut prendre des décisions facilement - A de la difficulté à prendre des décisions
        - (barre de 1--5)
        - Je ne sais pas/Préfère ne pas répondre
      
    + 20.5 Abandonne très facilement - N'abandonne jamais facilement
        - (barre de 1--5)
        - Je ne sais pas/Préfère ne pas répondre
      
    + 20.6 Pas du tout confiant(e) en soi - Très confiant(e) en soi
        - (barre de 1--5)
        - Je ne sais pas/Préfère ne pas répondre
      
    + 20.7 Se sent très inférieur(e) - Se sent très supérieur(e)
        - (barre de 1--5)
        - Je ne sais pas/Préfère ne pas répondre
      
    + 20.8 S'effondre sous la pression - Résiste bien à la pression
        - (barre de 1--5)
        - Je ne sais pas/Préfère ne pas répondre
      
    + 20.9 Pas du tout émotionnel(le) - Très émotionnel(le)
        - (barre de 1--5)
        - Je ne sais pas/Préfère ne pas répondre
      
    + 20.10 Pas du tout capable de se dévouer aux autres - Capable de se dévouer complètement aux autres
        - (barre de 1--5)
        - Je ne sais pas/Préfère ne pas répondre
      
    + 20.11 Très rude - Très doux (douce)
        - (barre de 1--5)
        - Je ne sais pas/Préfère ne pas répondre
      
    + 20.12 Pas très aidant(e) avec les autres - Très aidant(e) avec les autres
        - (barre de 1--5)
        - Je ne sais pas/Préfère ne pas répondre
      
    + 20.13 Pas très gentil(le) - Très gentil(le)
        - (barre de 1--5)
        - Je ne sais pas/Préfère ne pas répondre
      
    + 20.14 Pas du tout conscient(e) des sentiments des autres - Très conscient(e) des sentiments des autres
        - (barre de 1--5)
        - Je ne sais pas/Préfère ne pas répondre
      
    + 20.15 Pas du tout compréhensif(ive) des autres - Très compréhensif(ive) des autres
        - (barre de 1--5)
        - Je ne sais pas/Préfère ne pas répondre
      
    + 20.16 Très froid(e) dans les relations avec les autres - Très chaud(e) dans les relations avec les autres
        - (barre de 1--5)
        - Je ne sais pas/Préfère ne pas répondre

21. Il est possible que nous faisions une enquête de suivi dans quelques années. Si tu acceptes d’être contacté(e) par courriel pour cette enquête, quelle est ton adresse courriel actuelle? Garde le champ vide si tu ne veux pas être recontacté(e) pour cela.
  - (Champ libre)

# 2022 Quebec Datagotchi Post-Election Survey French Questionnaire {#sec-appendix3}

## Socio-Economic Status

1. Quel est votre genre?

- Masculin
- Féminin
- Masculin (homme trans)
- Féminin (femme trans)
- Non-binaire
- Queer
- Agenre
- Préfère ne pas répondre

2. Parmi les appellations suivantes, laquelle décrit le mieux votre orientation sexuelle?

- Hétérosexuel(le)
- Gai ou lesbienne
- Bisexuel(le)
- Autre
- Préfère ne pas répondre

3. Quel âge avez-vous?

Veuillez indiquer votre âge

4. Laquelle des catégories suivantes vous décrit le mieux?

- Blanc
- Noir
- Autochtone
- Asiatique
- Hispanique
- Arabe
- Autre
- Préfère ne pas répondre

5. Parmi les catégories suivantes, laquelle décrit le mieux votre domaine d'emploi?

- Agriculteurs, bûcherons et pêcheurs
- Propriétaires de magasins et d'usines
- Professions libérales
- Cadres et fonctionnaires
- Cols blancs
- Ouvriers
- Vente et services
- Au foyer
- Étudiants et sans profession

6. Approximativement, dans laquelle des catégories suivantes le revenu total de votre ménage, avant impôts, se situe-t-il?

- Aucun revenu
- 1\$ à 30 000\$
- 30 001\$ à 60 000\$
- 60 001\$ à 90 000\$
- 90 001 à 110 000\$
- 110 001\$ à 150 000\$
- 150 001\$ à 200 000\$
- Plus de 200 000\$

7. Quel est votre plus haut niveau de scolarité complété?

- Aucune scolarité
- École primaire
- École secondaire
- Collège, CÉGEP ou Collège classique
- Baccalauréat
- Maîtrise
- Doctorat

8. Quelle est votre religion, si vous en avez une?

- Aucune/Athée
- Agnostique
- Bouddhisme
- Hindou
- Judaïsme
- Musulman
- Sikhisme
- Catholique
- Protestantisme
- Orthodoxe
- Autre (veuillez préciser) \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
- Préfère ne pas répondre

9. Quel est votre degré d'attachement à cette église, dénomination religieuse ou communauté religieuse ?

- Très faible
- Plutôt faible
- Modéré
- Plutôt fort
- Très fort

10. Combien d'enfant ayant moins de 18 ans vivent avec vous?

- 0
- 1
- 2
- 3
- 4
- 5
- Plus de 5

11. Quel est votre statut matrimonial?

- Célibataire
- Marié(e)
- Conjoint de fait
- Veuf/veuve
- Divorcé/séparé

|  |
| --- |

12. Dans quel pays êtes-vous né(e)?

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

13. Êtes-vous...

- En emploi à temps plein
- En emploi à temps partiel
- Étudiant
- Retraité
- Sans emploi

14. Comment décririez-vous l'endroit où vous vivez?

- Ville
- Banlieu
- Petite ville
- Campagne/village

15. Quel est votre secteur d'emploi

- Secteur public
- Secteur privé
- Secteur associatif
- Ne travaille pas dans un emploi formel

## Attitudes

16. Quel est l'enjeu le plus important pour vous, personnellement?

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

17. Quel que soit le parti pour lequel vous avez l'intention de voter à l'occasion de la prochaine élection provinciale québécoise, en général, quelle est la probabilité que vous appuyiez [Sur une échelle de 0 à 10, où 0 signifie très peu probable, et 10 très probable] :

|
 | Préfère ne pas répondre |
| --- | --- |

|
 | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |

| Coalition avenir Québec (CAQ) |  |
| --- | --- |
| Parti libéral du Québec (PLQ) |  |
| Parti Québécois (PQ) |  |
| Québec solidaire (QS) |  |
| Parti conservateur du Québec (PCQ) |  |

18. Quel que soit le parti pour lequel vous avez l'intention de voter à l'occasion de la prochaine élection fédérale canadienne, en général, quelle est la probabilité que vous appuyiez [Sur une échelle de 0 à 10, où 0 signifie très peu probable, et 10 très probable] :

|
 | Préfère ne pas répondre |
| --- | --- |

|
 | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |

| Parti libéral du Canada (PLC) |  |
| --- | --- |
| Parti conservateur du Canada (PCC) |  |
| Nouveau Parti démocratique (NPD) |  |
| Bloc Québécois (BQ) |  |
| Parti vert du Canada (PV) |  |

19. Lors d'une élection, certaines personnes ne peuvent pas voter parce qu'elles sont malades ou occupées, ou pour une autre raison. Avez-vous voté aux élections provinciales québécoises de 2022 ?

- Oui
- Non

20. Pour quel parti avez-vous voté lors des élections provinciales québécoises de 2022?

- Coalition Avenir Québec
- Parti libéral du Québec
- Parti Québécois
- Québec Solidaire
- Parti conservateur du Québec
- Autre parti (veuillez spécifier) \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
- Préfère ne pas répondre

21. En politique, nous discutons parfois de "gauche" et "droite". Où est-ce que vous vous situerez sur l'échelle du placement gauche-droite? L'échelle va de 0 à 10 : 0 signifie que vous vous situez très à gauche, 10 signifie que vous vous situez très à droite (5 est le centre).

|
 | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |

| Veuillez déplacer le curseur |  |
| --- | --- |

22. En politique provinciale québécoise, vous considérez-vous habituellement comme étant...

- Caquiste (CAQ)
- Libéral (PLQ)
- Péquiste (PQ)
- Solidaire (QS)
- Conservateur (PCQ)
- Vert (PVQ)
- Un autre parti
- Aucun de ces partis
- Je ne sais pas/Préfère ne pas répondre

23. En utilisant l'échelle ci-dessous, comment évaluez-vous votre niveau de connaissances politiques?

- Très élevé
- Élevé
- Ni élevé ni faible
- Faible
- Très faible

24. Quel est votre degré d'accord avec les énoncés suivants?

|
 | Fortement en accord | Plutôt en accord | Ni en accord ni en désaccord | Plutôt en désaccord | Fortement en désaccord |
| --- | --- | --- | --- | --- | --- |
| Est-ce que vous accepteriez que la Taxe de Vente du Québec augmente et passe de 9.975% à 10.575% pour avoir accès à des soins dentaires et psychologiques gratuits? |
-
 |
-
 |
-
 |
-
 |
-
 |
| --- | --- | --- | --- | --- | --- |
| Est-ce qu'il est légitime que le gouvernement impose à tous les travailleurs de payer 0.5% de leur revenu (jusqu'à concurrence de 430$) pour s'assurer des deux parents d'un nouveau-né puisse recevoir 70% de son salaire pour rester à la maison avec son enfant pendant 50 semaines. |
-
 |
-
 |
-
 |
-
 |
-
 |
| Est-ce que vous accepteriez que le gouvernement diminue la Taxe de Vente du Québec pour qu'elle passe de 9.975% à 9.575%, mais que les frais de scolarité à l'université passent de 3000\$ à 7000\$ par année? |
-
 |
-
 |
-
 |
-
 |
-
 |

25. Si le gouvernement avait des surplus budgétaires, est-ce qu'il devrait surtout réduire les impôts ou surtout augmenter les dépenses en éducation ou en santé.

- Surtout augmentant les dépenses en éducation ou en santé
- Surtout réduisant les impôts

26. Si le gouvernement devait réduire son déficit budgétaire, est-ce qu'il devrait le faire surtout en augmentant les impôts ou surtout en réduisant les dépenses en éducation ou en santé.

- Surtout augmentant les impôts
- Surtout réduisant les dépenses en éducation ou en santé

27. Dans quelle mesure êtes-vous d'accord avec l'affirmation suivante : "Les impôts sont déjà élevés. Le gouvernement ne devrait plus prélever davantage d'argent auprès des citoyens par le biais des impôts."

- Fortement en accord
- Plutôt en accord
- Plutôt en désaccord
- Fortement en désaccord

28. Les gens ont différentes façons de se définir. Comment diriez-vous que vous vous considérez?

- Uniquement comme Canadien(ne)
- D'abord comme Canadien(ne), puis comme Québécois(e)
- Également comme Canadien(ne) puis comme Québécois(e)
- D'abord comme Québécois(e)
- Uniquement comme québécois(e)
- Autre

29. Le Québec devrait devenir un État indépendant.

- Fortement en désaccord
- Modérément en désaccord
- Un peu en désaccord
- Ni en accord ni en désaccord
- Un peu en accord
- Modérément en accord
- Fortement en accord

30. Est-ce que vous considérez que votre situation économique s'est améliorée, est restée la même, ou s'est détériorée pendant les 12 derniers mois?

- Améliorée
- Restée la même
- Détériorée

31. D'une manière générale, diriez-vous que l'on peut faire confiance à la plupart des gens ou que l'on ne peut pas être trop prudent dans ses relations avec les autres? Veuillez utiliser cette échelle de 0 à 10, où 0 signifie que vous ne pouvez pas être trop prudent et 10 que vous pouvez faire confiance à la plupart des gens.

|
 | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |

| Déplacez le curseur |  |
| --- | --- |

32. Je considère que je reçois ma juste part des services publics, considérant les taxes et impôts que je paie.

- Fortement en accord
- Plutôt en accord
- Plutôt en désaccord
- Fortement en désaccord

33. Qui est le ou la ministre des Finances du Canada?

- Eric Girard
- Chrystia Freeland
- Steven Guilbault
- Pierre Poilièvre
- Mélanie Joly
- Ne sait pas

34. Pensez-vous que le Canada devrait admettre:

- Plus d'immigrants
- Moins d'immigrants
- À peu près le même nombre d'immigrants

35. Pensez-vous que le Canada devrait admettre:

- Plus de réfugiés
- Moins de réfugiés
- À peu près le même nombre de réfugiés

36. Le Canada devrait accepter les réfugiés provenant de pays aux prises avec des catastrophes écologiques.

- Fortement en accord
- Plutôt d'accord
- Neutre
- Plutôt en désaccord
- Fortement en désaccord

37. Nous devrions développer les pistes cyclables et le transport collectif, même si cela implique de réduire l'espace pour les voitures.

- Fortement en accord
- Plutôt d'accord
- Neutre
- Plutôt en désaccord
- Fortement en désaccord

38. Les changements climatiques constituent une menace pour moi au cours de ma vie.

- Fortement en accord
- Plutôt d'accord
- Neutre
- Plutôt en désaccord
- Fortement en désaccord

39. Si les choses continuent ainsi, nous connaîtrons bientôt une catastrophe écologique majeure.

- Fortement en accord
- Plutôt d'accord
- Neutre
- Plutôt en désaccord
- Fortement en désaccord

40. Les changements climatiques mèneront à la fin de l'humanité.

- Fortement en accord
- Plutôt d'accord
- Neutre
- Plutôt en désaccord
- Fortement en désaccord

41. Les citoyens mécontents du gouvernement ne doivent jamais recourir à la violence pour exprimer leurs sentiments

- Fortement en accord
- Plutôt d'accord
- Neutre
- Plutôt en désaccord
- Fortement en désaccord

42. À quel point seriez-vous prêt à tolérer les actions politiques suivantes pour l'avancement de la cause climatique?

|
 | Aucune tolérance | Tolérance faible | Tolérance moyenne | Tolérance élevée |
| --- | --- | --- | --- | --- |
| Signer une pétition |
-
 |
-
 |
-
 |
-
 |
| --- | --- | --- | --- | --- |
| Boycotter des produits et compagnies |
-
 |
-
 |
-
 |
-
 |
| Désinvestir des placements |
-
 |
-
 |
-
 |
-
 |
| Participer à une manifestation |
-
 |
-
 |
-
 |
-
 |
| Occuper temporairement un espace public |
-
 |
-
 |
-
 |
-
 |
| S'attacher à un arbre ou un véhicule |
-
 |
-
 |
-
 |
-
 |
| Bloquer un pont ou une route |
-
 |
-
 |
-
 |
-
 |
| Bloquer la construction d'un oléoduc (pipeline) |
-
 |
-
 |
-
 |
-
 |
| Faire du vandalisme sur des objets |
-
 |
-
 |
-
 |
-
 |
| Saboter des infrastructures, des véhicules, etc |
-
 |
-
 |
-
 |
-
 |
| Tirer un objet sur des infrastructures, des véhicules, etc. |
-
 |
-
 |
-
 |
-
 |
| Affronter des policiers dans une manifestation |
-
 |
-
 |
-
 |
-
 |
| Violenter des individus en position de pouvoir |
-
 |
-
 |
-
 |
-
 |

43. Si vous ouvriez un site Web d'information et que vous voyiez les articles suivants, dans quelle mesure seriez-vous intéressé par la lecture de chaque article? Déplacez la barre vis-à-vis un nombre compris entre 0 et 10, où 0 signifie « Pas du tout intéressé, je ne le lirai pas » et 10 signifie « Très intéressé, je le lirai fort probablement »

|
 | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |

| Santé (ex.: restrictions en cas de pandémie, conditions de travail des infirmiers(ères)) | |
| --- | --- |
| Affaires internationales (ex.: conflits diplomatiques entre le Canada et la Chine, guerre en Ukraine) | |
| Loi et crime (ex.: financement de la police, peines pour des crimes violents) | |
| Éducation (ex.: frais de scolarité universitaires, financement des écoles publiques et privées) | |
| Politique partisane (ex.: les élections fédérales, les partis politiques) | |

44. Quel est votre intérêt pour la politique en général? Glissez la barre sur un chiffre de 0 à 10, où 0 indique aucun intérêt du tout et 10 indique beaucoup d'intérêt.

|
 | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |

| Déplacez le curseur |  |
| --- | --- |

45. Certains pensent que le gouvernement à Ottawa devrait faire tout en son pouvoir pour améliorer la situation sociale et économique des personnes noires. D'autres estiment que le gouvernement ne devrait faire aucun effort particulier pour aider les personnes noires. Et, bien sûr, d'autres personnes ont des opinions quelque part entre les deux. Où vous situeriez-vous sur l'échelle suivante, où 1 signifie que le gouvernement devrait aider les personnes noires et 7 que le gouvernement ne devrait pas aider les personnes noires)?

- 1 (Le gouvernement devrait aider les personne noires)
- 2
- 3
- 4
- 5
- 6
- 7 (Le gouvernement ne devrait pas aider les personnes noires)

46. Personnellement, êtes-vous en accord ou en désaccord avec l'imposition de quotas pour qu'il y ait plus de personnes noires en politique?

- Fortement en désaccord
- Plutôt en désaccord
- Ni accord ni en désaccord
- Plutôt d'accord
- Fortement en accord

47. Sur l'échelle suivante, où 1 correspond à « équitablement » et 7 à « inéquitablement », comment pensez-vous que la police traite les personnes noires par rapport aux personnes blanches au Canada?

- 1 (Équitablement)
- 2
- 3
- 4
- 5
- 6
- 7 (Inéquitablement)

48. Selon vous, quel est le degré de discrimination au Canada aujourd'hui contre chacun des groupes suivants?

|
 | Aucune | Un peu | Une quantité modérée | Beaucoup | Énormément |
| --- | --- | --- | --- | --- | --- |
| Les noirs |
-
 |
-
 |
-
 |
-
 |
-
 |
| --- | --- | --- | --- | --- | --- |
| Les asiatiques |
-
 |
-
 |
-
 |
-
 |
-
 |
| Les blancs |
-
 |
-
 |
-
 |
-
 |
-
 |
| Les autochtones |
-
 |
-
 |
-
 |
-
 |
-
 |
| Les hispaniques |
-
 |
-
 |
-
 |
-
 |
-
 |
| Les arabes |
-
 |
-
 |
-
 |
-
 |
-
 |

## Perceptions

49. À votre avis, quel parti gérerait le mieux l'enjeu du coût de la vie?

- CAQ
- PLQ
- PQ
- QS
- PCQ

50. Que représente l'enjeu du coût de la vie pour vous, personnellement?

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

51. Il serait possible d'accomplir mes activités quotidiennes sans voiture.

- Fortement en accord
- Plutôt d'accord
- Neutre
- Plutôt en désaccord
- Fortement en désaccord

## Lifestyle

52. En comparaison avec le reste de la société, comment évaluez-vous votre consommation d'alcool ?

- Très en-dessous de la moyenne
- En-dessous de la moyenne
- Dans la moyenne
- Au-dessus de la moyenne
- Très au-dessus de la moyenne

53. Comment percevez-vous les gens qui sont contre la consommation d'alcool? [Sur un thermomètre de sentiment allant de 0 (Très négatif) à 100 (Très positif)]

|
 | 0 | 10 | 20 | 30 | 40 | 50 | 60 | 70 | 80 | 90 | 100 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |

| Déplacez le curseur | |
| --- | --- |

|  |
| --- |

54. Au cours des 12 derniers mois, à quelle fréquence avez-vous consommé des boissons alcoolisées ?

- Moins d'une fois par mois
- Une fois par mois
- 2 à 3 fois par mois
- Une fois par semaine
- 2 à 3 fois par semaine
- 4 à 6 fois par semaine
- Tous les jours
- Préfère ne pas répondre
- Ne sais pas

55. Au cours du dernier mois, combien de fois avez-vous bu [5 pour les hommes /4 pour les femmes] verres ou plus d'alcool à une même occasion ?

- Jamais
- Moins d'une fois
- Une fois
- 2 à 3 fois
- Une fois par semaine
- Plus d'une fois par semaine
- Tous les jours
- Préfère ne pas répondre
- Ne sais pas

56. À quelle fréquence lisez-vous des livres?

- Jamais
- Presque jamais
- Parfois
- Souvent
- Très souvent

57. Quel est votre livre préféré?

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

58. Quel est votre genre de roman préféré?

- Roman policier
- Roman historique
- Roman picaresque
- Roman d'amour
- Roman philosophique
- Roman d'aventure
- Autre (veuillez préciser) \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

## Other Opinions

59. Le gouvernement doit réduire les inégalités de revenus entre les riches et les pauvres.

- Fortement en accord
- Plutôt en accord
- Ni en accord ni en désaccord
- Plutôt en désaccord
- Fortement en désaccord

60. Voici une liste de domaines où l'État intervient. Spécifiez si vous souhaitez que le gouvernement dépense plus ou moins dans chaque domaine. Soyez conscients que dépenser plus ou beaucoup plus peut occasionner une augmentation des taxes et impôts.

|
 | Dépenser beaucoup plus | Dépenser plus | Dépenser le même montant qu'actuellement | Dépenser moins | Dépenser beaucoup moins |
| --- | --- | --- | --- | --- | --- |
| Soins de santé |
-
 |
-
 |
-
 |
-
 |
-
 |
| --- | --- | --- | --- | --- | --- |
| Soins à domicile pour les personnes âgées |
-
 |
-
 |
-
 |
-
 |
-
 |
| Services de garde |
-
 |
-
 |
-
 |
-
 |
-
 |
| Éducation |
-
 |
-
 |
-
 |
-
 |
-
 |
| Les prestations aux personnes à faible revenu |
-
 |
-
 |
-
 |
-
 |
-
 |
| Les prestations aux familles |
-
 |
-
 |
-
 |
-
 |
-
 |

61. Imaginez que le gouvernement ait les moyens d'augmenter certains programmes sociaux, mais pas tous. Parmi les améliorations suivantes des programmes sociaux, lesquels vous semblent les plus importantes ? Vous devez attribuer 100 points. Donnez plus de points aux améliorations que vous considérez comme plus importantes et moins de points à celles que vous considérez comme moins importantes. Le gouvernement devrait...

|
 | 0 | 10 | 20 | 30 | 40 | 50 | 60 | 70 | 80 | 90 | 100 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |

| Améliorer les soins à domicile pour les personnes âgées | |
| --- | --- |
| Augmenter les prestations offertes aux familles | |
| Augmenter le nombre de places dans les services de garde | |
| Améliorer la qualité du réseau d'éducation | |
| Améliorer l'accès au réseau de la santé | |
| Améliorer la lutte à la pauvreté | |

62. Selon vous, quel est le meilleur...

|
 | Veuillez inscrire votre réponse dans l'encadré. | Cochez la case si vous n'en connaissez aucun. |
| --- | --- | --- |
|
 | Question ouverte | Je n'en connais aucun |
| Livre canadien de tous les temps? |
 |
-
 |
| Album de musique canadien de tous les temps? |
 |
-
 |
| Film canadien de tous les temps? |
 |
-
 |
| Journal quotidien canadien de tous les temps? |
 |
-
 |

63. Nous souhaitons savoir si les gens connaissent mieux certains types de personnalités publiques que d'autres au Canada. Sans consulter d'autres sources, veuillez nommer une personnalité publique francophone canadienne travaillant:

|
 | Veuillez inscrire votre réponse dans l'encadré. | Cochez la case si vous n'en connaissez aucun. |
| --- | --- | --- |
|
 | Question ouverte | Je n'en connais aucun |
| Dans les médias (ex.: animateur/animatrice, journaliste, ...) |
 |
-
 |
| Comme chanteur/chanteuse |
 |
-
 |
| Comme acteur/actrice |
 |
-
 |
| Comme écrivain/écrivaine |
 |
-
 |

64. Nous souhaitons savoir si les gens connaissent mieux certains types de personnalités publiques que d'autres au Canada. Sans consulter d'autres sources, veuillez nommer une personnalité publique anglophone canadienne travaillant:

|
 | Veuillez inscrire votre réponse dans l'encadré. | Cochez la case si vous n'en connaissez aucun. |
| --- | --- | --- |
|
 | Question ouverte | Je n'en connais aucun |
| Dans les médias (ex.: animateur/animatrice, journaliste, ...) |
 |
-
 |
| Comme chanteur/chanteuse |
 |
-
 |
| Comme acteur/actrice |
 |
-
 |
| Comme écrivain/écrivaine |
 |
-
 |

65. Combien d'amis avez-vous de chacun des groupes suivants? Par "amis", nous référons à des personnes que vous appréciez et connaissez bien, mais qui ne sont pas des membres de votre famille.

|
 | 1-2 | 3-4 | 5-6 | 7 ou plus |
| --- | --- | --- | --- | --- |
| Des gens de langue maternelle francophone |
-
 |
-
 |
-
 |
-
 |
| --- | --- | --- | --- | --- |
| Des gens de langue maternelle anglophone |
-
 |
-
 |
-
 |
-
 |
| Des gens d'une autre langue maternelle |
-
 |
-
 |
-
 |
-
 |

66. Sur une échelle de 0 à 10, comment évaluez-vous vos compétences dans les langues suivantes ?

|
 | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |

| Le français |  |
| --- | --- |
| L'anglais |  |

# Political Interest Transmission by Parents (Control Variables Added) {#sec-appendix4}

## Topics Parents Discuss the Most

Table: Interest in topic by gender of parent who discusses that topic the most {#tbl-lmeParent}

|                                    | Health care | International affairs | Law and crime | Education | Partisan politics | 
|:-----------------------------------|------------:|----------------------:|--------------:|----------:|------------------:|
| **Results among boys**             |             |                       |               |           |                   | 
| (Intercept)                        |   4.631***  |        6.333***       |    5.504***   |  4.260*** |      4.601***     | 
|                                    |   (0.379)   |        (0.251)        |    (0.222)    |  (0.340)  |      (0.286)      | 
| Health care (1 = mother)           |    -0.411   |                       |               |           |                   | 
|                                    |   (0.401)   |                       |               |           |                   | 
| International affairs (1 = mother) |             |         -0.332        |               |           |                   | 
|                                    |             |        (0.401)        |               |           |                   | 
| Law and crime (1 = mother)         |             |                       |     -0.242    |           |                   | 
|                                    |             |                       |    (0.381)    |           |                   | 
| Education (1 = mother)             |             |                       |               |   0.286   |                   | 
|                                    |             |                       |               |  (0.379)  |                   | 
| Partisan politics (1 = mother)     |             |                       |               |           |       -0.182      | 
|                                    |             |                       |               |           |      (0.480)      | 
| SD (Intercept Class)               |    0.705    |         0.820         |     0.349     |   0.649   |       0.582       | 
| SD (Observations)                  |    2.361    |         2.483         |     2.638     |   2.694   |       2.973       | 
| Num.Obs.                           |     241     |          225          |      228      |    252    |        192        | 
| R2 Marg.                           |    0.004    |         0.003         |     0.002     |   0.002   |       0.001       | 
|:-----------------------------------|------------:|----------------------:|--------------:|----------:|------------------:|
| **Results among girls**            |             |                       |               |           |                   | 
| (Intercept)                        |   4.138***  |        5.057***       |    5.652***   |  4.602*** |      3.449***     | 
|                                    |   (0.424)   |        (0.240)        |    (0.265)    |  (0.423)  |      (0.279)      | 
| Health care (1 = mother)           |    0.158    |                       |               |           |                   | 
|                                    |   (0.442)   |                       |               |           |                   | 
| International affairs (1 = mother) |             |         -0.118        |               |           |                   | 
|                                    |             |        (0.415)        |               |           |                   | 
| Law and crime (1 = mother)         |             |                       |     0.047     |           |                   | 
|                                    |             |                       |    (0.397)    |           |                   | 
| Education (1 = mother)             |             |                       |               |   -0.434  |                   | 
|                                    |             |                       |               |  (0.445)  |                   | 
| Partisan politics (1 = mother)     |             |                       |               |           |       0.110       | 
|                                    |             |                       |               |           |      (0.475)      | 
| SD (Intercept Class)               |    0.665    |         0.345         |     0.492     |   0.849   |       0.360       | 
| SD (Observations)                  |    2.376    |         2.687         |     2.777     |   2.599   |       2.748       | 
| Num.Obs.                           |     237     |          199          |      212      |    228    |        156        | 
| R2 Marg.                           |    0.001    |         0.000         |     0.000     |   0.004   |       0.000       | 
|:-----------------------------------|------------:|----------------------:|--------------:|----------:|------------------:|

__Note:__
^^ + p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001

__Note:__
^^ Multilevel regression with random effects at the classroom level

## Topics Most Often Discussed with Mothers

Table: Interest in topic most often discussed with one's mother {#tbl-lmeMother}

|                         | Health care | International affairs | Law and crime | Education | Partisan politics | 
|:------------------------|------------:|----------------------:|--------------:|----------:|------------------:|
| **Results among boys**  |             |                       |               |           |                   | 
| (Intercept)             |   4.093***  |        5.981***       |    5.077***   |  4.339*** |      4.210***     | 
|                         |   (0.227)   |        (0.208)        |    (0.167)    |  (0.249)  |      (0.207)      | 
| Health care             |    0.355    |                       |               |           |                   | 
|                         |   (0.303)   |                       |               |           |                   | 
| International affairs   |             |         1.113         |               |           |                   | 
|                         |             |        (0.733)        |               |           |                   | 
| Law and crime           |             |                       |     1.747*    |           |                   | 
|                         |             |                       |    (0.677)    |           |                   | 
| Education               |             |                       |               |   0.253   |                   | 
|                         |             |                       |               |  (0.335)  |                   | 
| Partisan politics       |             |                       |               |           |       1.519       | 
|                         |             |                       |               |           |      (1.231)      | 
| SD (Intercept Class)    |    0.706    |         0.631         |     0.000     |   0.567   |       0.537       | 
| SD (Observations)       |    2.377    |         2.722         |     2.706     |   2.744   |       2.931       | 
| Num.Obs.                |     275     |          277          |      278      |    277    |        277        | 
| R2 Marg.                |    0.005    |         0.008         |     0.023     |   0.002   |       0.005       | 
|:------------------------|------------:|----------------------:|--------------:|----------:|------------------:|
| **Results among girls** |             |                       |               |           |                   | 
| (Intercept)             |   4.046***  |        4.739***       |    5.226***   |  3.834*** |      3.136***     | 
|                         |   (0.225)   |        (0.202)        |    (0.196)    |  (0.277)  |      (0.167)      | 
| Health care             |    0.278    |                       |               |           |                   | 
|                         |   (0.310)   |                       |               |           |                   | 
| International affairs   |             |         1.226+        |               |           |                   | 
|                         |             |        (0.644)        |               |           |                   | 
| Law and crime           |             |                       |    3.057***   |           |                   | 
|                         |             |                       |    (0.620)    |           |                   | 
| Education               |             |                       |               |  0.881**  |                   | 
|                         |             |                       |               |  (0.338)  |                   | 
| Partisan politics       |             |                       |               |           |       2.864+      | 
|                         |             |                       |               |           |      (1.579)      | 
| SD (Intercept Class)    |    0.691    |         0.590         |     0.438     |   0.974   |       0.000       | 
| SD (Observations)       |    2.370    |         2.651         |     2.761     |   2.579   |       2.719       | 
| Num.Obs.                |     270     |          267          |      265      |    267    |        267        | 
| R2 Marg.                |    0.003    |         0.013         |     0.084     |   0.024   |       0.012       | 
|:------------------------|------------:|----------------------:|--------------:|----------:|------------------:|

__Note:__
^^ + p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001

__Note:__
^^ Multilevel regression with random effects at the classroom level

## Topics Most Often Discussed with Fathers

Table: Interest in topic most often discussed with one's father {#tbl-lmeFather}

|                         | Health care | International affairs | Law and crime | Education | Partisan politics | 
|:------------------------|------------:|----------------------:|--------------:|----------:|------------------:|
| **Results among boys**  |             |                       |               |           |                   | 
| (Intercept)             |   4.275***  |        5.838***       |    4.987***   |  4.479*** |      4.110***     | 
|                         |   (0.194)   |        (0.215)        |    (0.175)    |  (0.219)  |      (0.215)      | 
| Health care             |    -0.206   |                       |               |           |                   | 
|                         |   (0.499)   |                       |               |           |                   | 
| International affairs   |             |         0.557         |               |           |                   | 
|                         |             |        (0.343)        |               |           |                   | 
| Law and crime           |             |                       |     1.013*    |           |                   | 
|                         |             |                       |    (0.424)    |           |                   | 
| Education               |             |                       |               |   0.037   |                   | 
|                         |             |                       |               |  (0.405)  |                   | 
| Partisan politics       |             |                       |               |           |      1.887**      | 
|                         |             |                       |               |           |      (0.644)      | 
| SD (Intercept Class)    |    0.650    |         0.370         |     0.000     |   0.614   |       0.626       | 
| SD (Observations)       |    2.336    |         2.730         |     2.677     |   2.715   |       2.849       | 
| Num.Obs.                |     278     |          281          |      281      |    281    |        280        | 
| R2 Marg.                |    0.001    |         0.009         |     0.020     |   0.000   |       0.030       | 
|:------------------------|------------:|----------------------:|--------------:|----------:|------------------:|
| **Results among girls** |             |                       |               |           |                   | 
| (Intercept)             |   4.057***  |        4.816***       |    5.213***   |  4.052*** |      3.167***     | 
|                         |   (0.205)   |        (0.238)        |    (0.214)    |  (0.261)  |      (0.185)      | 
| Health care             |    0.383    |                       |               |           |                   | 
|                         |   (0.444)   |                       |               |           |                   | 
| International affairs   |             |         -0.018        |               |           |                   | 
|                         |             |        (0.371)        |               |           |                   | 
| Law and crime           |             |                       |    1.559**    |           |                   | 
|                         |             |                       |    (0.507)    |           |                   | 
| Education               |             |                       |               |   0.036   |                   | 
|                         |             |                       |               |  (0.395)  |                   | 
| Partisan politics       |             |                       |               |           |       0.199       | 
|                         |             |                       |               |           |      (0.653)      | 
| SD (Intercept Class)    |    0.704    |         0.674         |     0.537     |   0.994   |       0.290       | 
| SD (Observations)       |    2.341    |         2.678         |     2.787     |   2.578   |       2.724       | 
| Num.Obs.                |     259     |          257          |      256      |    257    |        257        | 
| R2 Marg.                |    0.003    |         0.000         |     0.035     |   0.000   |       0.000       | 
|:------------------------|------------:|----------------------:|--------------:|----------:|------------------:|

__Note:__
^^ + p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001

__Note:__
^^ Multilevel regression with random effects at the classroom level

# Political Interest Transmission by Peers (Control Variables Added) {#sec-appendix5}

## Topics Most Often Discussed with Female Friends

Table: Interest in topic most often discussed with one's female friends {#tbl-lmeFemaleFriendsAlt}

|                         | Health care | International affairs | Law and crime | Education | Partisan politics | 
|:------------------------|------------:|----------------------:|--------------:|----------:|------------------:|
| **Results among boys**  |             |                       |               |           |                   | 
| (Intercept)             |    -0.009   |         13.435        |     13.722    |   -2.720  |      -17.730      | 
|                         |   (18.237)  |        (17.524)       |    (16.447)   |  (18.508) |      (19.181)     | 
| Health care             |    -0.488   |                       |               |           |                   | 
|                         |   (0.645)   |                       |               |           |                   | 
| Age                     |    -0.054   |         -1.319        |     -1.903    |   -0.224  |       2.666       | 
|                         |   (2.535)   |        (2.448)        |    (2.294)    |  (2.572)  |      (2.679)      | 
| Age squared             |    0.004    |         0.043         |     0.065     |   0.020   |       -0.094      | 
|                         |   (0.088)   |        (0.085)        |    (0.080)    |  (0.089)  |      (0.093)      | 
| Race (1 = white)        |    -0.162   |         0.796         |     -0.178    |   -0.516  |       0.345       | 
|                         |   (0.547)   |        (0.565)        |    (0.515)    |  (0.540)  |      (0.612)      | 
| Immigrant               |    -1.125   |         -1.352        |     -0.092    |   -1.278  |       -1.028      | 
|                         |   (0.839)   |        (0.846)        |    (0.780)    |  (0.835)  |      (0.922)      | 
| English spoken at home  |    -0.439   |         -1.140        |     -0.657    |   1.554   |       0.819       | 
|                         |   (1.320)   |        (1.283)        |    (1.194)    |  (1.327)  |      (1.403)      | 
| French spoken at home   |    0.370    |         -0.534        |     0.262     |   0.803   |       1.229       | 
|                         |   (0.802)   |        (0.799)        |    (0.740)    |  (0.801)  |      (0.874)      | 
| Agency                  |    4.059*   |         1.161         |     3.824*    |   2.434   |       2.181       | 
|                         |   (1.706)   |        (1.688)        |    (1.536)    |  (1.643)  |      (1.825)      | 
| Communality             |    2.593    |         3.612*        |     3.847*    |  5.945*** |       2.040       | 
|                         |   (1.687)   |        (1.662)        |    (1.523)    |  (1.665)  |      (1.799)      | 
| International affairs   |             |         0.168         |               |           |                   | 
|                         |             |        (0.553)        |               |           |                   | 
| Law and crime           |             |                       |     1.522*    |           |                   | 
|                         |             |                       |    (0.670)    |           |                   | 
| Education               |             |                       |               |  1.297**  |                   | 
|                         |             |                       |               |  (0.479)  |                   | 
| Partisan politics       |             |                       |               |           |       0.172       | 
|                         |             |                       |               |           |      (1.256)      | 
| **Results among girls** |             |                       |               |           |                   | 
| SD (Intercept Class)    |    0.801    |         0.000         |     0.439     |   1.059   |       0.000       | 
| SD (Observations)       |    2.397    |         2.503         |     2.272     |   2.347   |       2.740       | 
| Num.Obs.                |     116     |          116          |      116      |    116    |        116        | 
| R2 Marg.                |    0.085    |         0.096         |     0.161     |   0.230   |       0.094       | 
|:------------------------|------------:|----------------------:|--------------:|----------:|------------------:|
| (Intercept)             |    -7.187   |         12.921        |     -8.833    |   -6.657  |      35.292*      | 
|                         |   (13.199)  |        (14.961)       |    (16.039)   |  (14.911) |      (14.656)     | 
| Health care             |    0.303    |                       |               |           |                   | 
|                         |   (0.466)   |                       |               |           |                   | 
| Age                     |    1.111    |         -1.313        |     1.865     |   1.137   |      -4.333*      | 
|                         |   (1.843)   |        (2.093)        |    (2.249)    |  (2.077)  |      (2.046)      | 
| Age squared             |    -0.027   |         0.046         |     -0.060    |   -0.028  |       0.146*      | 
|                         |   (0.064)   |        (0.073)        |    (0.078)    |  (0.072)  |      (0.071)      | 
| Race (1 = white)        |    0.261    |         0.184         |     -0.455    |   -0.038  |       -0.141      | 
|                         |   (0.465)   |        (0.526)        |    (0.547)    |  (0.515)  |      (0.538)      | 
| Immigrant               |    -0.337   |         -1.058        |    -2.367**   |   0.426   |       -0.220      | 
|                         |   (0.634)   |        (0.740)        |    (0.760)    |  (0.697)  |      (0.749)      | 
| English spoken at home  |    -0.109   |        -1.613+        |     -0.934    |   0.559   |       -0.342      | 
|                         |   (0.771)   |        (0.850)        |    (0.902)    |  (0.868)  |      (0.841)      | 
| French spoken at home   |    0.061    |         -0.397        |     -0.362    |   0.888   |       -0.036      | 
|                         |   (0.541)   |        (0.628)        |    (0.643)    |  (0.593)  |      (0.640)      | 
| Agency                  |    -0.522   |         1.366         |     2.103     |   -0.336  |       1.597       | 
|                         |   (1.331)   |        (1.538)        |    (1.561)    |  (1.458)  |      (1.580)      | 
| Communality             |    1.514    |         1.023         |     -0.048    |   -0.279  |       -1.041      | 
|                         |   (1.377)   |        (1.551)        |    (1.616)    |  (1.523)  |      (1.600)      | 
| International affairs   |             |        1.813**        |               |           |                   | 
|                         |             |        (0.639)        |               |           |                   | 
| Law and crime           |             |                       |     0.522     |           |                   | 
|                         |             |                       |    (0.568)    |           |                   | 
| Education               |             |                       |               |   0.330   |                   | 
|                         |             |                       |               |  (0.447)  |                   | 
| Partisan politics       |             |                       |               |           |       4.166*      | 
|                         |             |                       |               |           |      (1.602)      | 
| SD (Intercept Class)    |    0.704    |         0.449         |     0.826     |   0.966   |       0.000       | 
| SD (Observations)       |    2.156    |         2.532         |     2.517     |   2.341   |       2.640       | 
| Num.Obs.                |     136     |          134          |      134      |    136    |        136        | 
| R2 Marg.                |    0.067    |         0.106         |     0.107     |   0.057   |       0.104       | 
|:------------------------|------------:|----------------------:|--------------:|----------:|------------------:|

__Note:__
^^ + p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001

__Note:__
^^ Multilevel regression with random effects at the classroom level

## Topics Most Often Discussed with Male Friends

Table: Interest in topic most often discussed with one's male friends {#tbl-lmeMaleFriendsAlt}

|                         | Health care | International affairs | Law and crime | Education | Partisan politics | 
|:------------------------|------------:|----------------------:|--------------:|----------:|------------------:|
| **Results among boys**  |             |                       |               |           |                   | 
| (Intercept)             |    -8.307   |         0.569         |     10.252    |   0.908   |      -11.642      | 
|                         |   (15.056)  |        (15.175)       |    (15.430)   |  (17.084) |      (17.410)     | 
| Health care             |    -0.649   |                       |               |           |                   | 
|                         |   (0.698)   |                       |               |           |                   | 
| Age                     |    1.120    |         0.143         |     -1.284    |   -0.474  |       1.695       | 
|                         |   (2.068)   |        (2.083)        |    (2.123)    |  (2.343)  |      (2.391)      | 
| Age squared             |    -0.034   |         -0.008        |     0.046     |   0.030   |       -0.061      | 
|                         |   (0.071)   |        (0.072)        |    (0.073)    |  (0.081)  |      (0.082)      | 
| Race (1 = white)        |    0.294    |        1.238**        |     -0.245    |   -0.245  |       0.491       | 
|                         |   (0.433)   |        (0.456)        |    (0.448)    |  (0.498)  |      (0.533)      | 
| Immigrant               |    -0.702   |        -1.312+        |    -1.443*    |  -1.311+  |       -0.792      | 
|                         |   (0.644)   |        (0.694)        |    (0.670)    |  (0.740)  |      (0.785)      | 
| English spoken at home  |    -1.069   |         -1.513        |     -0.422    |   0.388   |       0.180       | 
|                         |   (0.893)   |        (0.919)        |    (0.899)    |  (1.008)  |      (1.063)      | 
| French spoken at home   |    0.211    |         -0.785        |     0.026     |   0.446   |       0.914       | 
|                         |   (0.559)   |        (0.584)        |    (0.573)    |  (0.634)  |      (0.671)      | 
| Agency                  |   3.410**   |        3.650**        |    3.281**    |   1.659   |       3.254*      | 
|                         |   (1.175)   |        (1.244)        |    (1.220)    |  (1.343)  |      (1.429)      | 
| Communality             |    1.854    |        3.826**        |     2.880*    |  3.863**  |       2.400       | 
|                         |   (1.277)   |        (1.356)        |    (1.294)    |  (1.464)  |      (1.534)      | 
| International affairs   |             |        1.128**        |               |           |                   | 
|                         |             |        (0.392)        |               |           |                   | 
| Law and crime           |             |                       |    1.333**    |           |                   | 
|                         |             |                       |    (0.431)    |           |                   | 
| Education               |             |                       |               |   0.874+  |                   | 
|                         |             |                       |               |  (0.516)  |                   | 
| Partisan politics       |             |                       |               |           |       1.430       | 
|                         |             |                       |               |           |      (0.900)      | 
| **Results among girls** |             |                       |               |           |                   | 
| SD (Intercept Class)    |    0.753    |         0.222         |     0.000     |   0.793   |       0.000       | 
| SD (Observations)       |    2.232    |         2.430         |     2.387     |   2.562   |       2.800       | 
| Num.Obs.                |     171     |          172          |      171      |    171    |        171        | 
| R2 Marg.                |    0.100    |         0.216         |     0.150     |   0.125   |       0.094       | 
|:------------------------|------------:|----------------------:|--------------:|----------:|------------------:|
| (Intercept)             |   -23.389   |         22.422        |     7.096     |   -0.350  |      41.624*      | 
|                         |   (15.133)  |        (18.476)       |    (18.125)   |  (16.385) |      (17.237)     | 
| Health care             |    -0.210   |                       |               |           |                   | 
|                         |   (0.779)   |                       |               |           |                   | 
| Age                     |    3.392    |         -2.511        |     -0.549    |   0.192   |      -5.234*      | 
|                         |   (2.092)   |        (2.559)        |    (2.504)    |  (2.261)  |      (2.377)      | 
| Age squared             |    -0.102   |         0.086         |     0.031     |   0.008   |       0.172*      | 
|                         |   (0.072)   |        (0.088)        |    (0.086)    |  (0.078)  |      (0.082)      | 
| Race (1 = white)        |    0.319    |         -0.563        |     -0.586    |   -0.157  |       -0.083      | 
|                         |   (0.525)   |        (0.632)        |    (0.633)    |  (0.572)  |      (0.621)      | 
| Immigrant               |    -0.284   |         -0.590        |    -2.081*    |   0.852   |       -0.031      | 
|                         |   (0.643)   |        (0.780)        |    (0.787)    |  (0.682)  |      (0.760)      | 
| English spoken at home  |    -0.339   |         -1.374        |     -0.189    |   0.717   |       -0.312      | 
|                         |   (0.764)   |        (0.927)        |    (0.890)    |  (0.852)  |      (0.863)      | 
| French spoken at home   |    -0.021   |         0.189         |     0.324     |   0.911   |       0.450       | 
|                         |   (0.583)   |        (0.707)        |    (0.707)    |  (0.617)  |      (0.691)      | 
| Agency                  |    -0.162   |         1.243         |     -0.123    |   0.242   |       2.051       | 
|                         |   (1.410)   |        (1.698)        |    (1.705)    |  (1.480)  |      (1.685)      | 
| Communality             |    0.126    |         0.769         |     0.559     |   -1.241  |       -0.120      | 
|                         |   (1.445)   |        (1.744)        |    (1.737)    |  (1.566)  |      (1.685)      | 
| International affairs   |             |         0.679         |               |           |                   | 
|                         |             |        (0.597)        |               |           |                   | 
| Law and crime           |             |                       |     -0.595    |           |                   | 
|                         |             |                       |    (0.541)    |           |                   | 
| Education               |             |                       |               |   0.485   |                   | 
|                         |             |                       |               |  (0.551)  |                   | 
| Partisan politics       |             |                       |               |           |       2.332+      | 
|                         |             |                       |               |           |      (1.268)      | 
| SD (Intercept Class)    |    0.499    |         0.610         |     0.283     |   0.898   |       0.000       | 
| SD (Observations)       |    2.204    |         2.650         |     2.674     |   2.277   |       2.651       | 
| Num.Obs.                |     115     |          114          |      113      |    115    |        115        | 
| R2 Marg.                |    0.088    |         0.086         |     0.100     |   0.104   |       0.108       | 
|:------------------------|------------:|----------------------:|--------------:|----------:|------------------:|

__Note:__
^^ + p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001

__Note:__
^^ Multilevel regression with random effects at the classroom level
