project:
  type: book
book:
  title: "Gendered Political Socialization"
  subtitle: "Why Women and Men Still Differ in Political Interest"
  author: "Alexandre Fortier-Chouinard"
  date: last-modified
  date-format: "MMMM D, YYYY"
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-method.qmd
    - 03-develop.qmd
    - 04-parent.qmd
    - 05-peer.qmd
    - 06-conclu.qmd
    - 07-references.qmd
  appendices:
    - 08-appendix.qmd
bibliography: Thesis.bib
#filters:
#  - section-bibliographies
header-includes:
  - \widowpenalty10000
  - \clubpenalty10000
format:
  pdf:
    documentclass: scrreprt
