project:
  type: book
book:
  title: "The Roots of Political Interests"
  subtitle: "How Gender Still Shapes Childhood Socialization"
  author: "Alexandre Fortier-Chouinard"
  chapters:
    - index.qmd
    - 02-method.qmd
    - 03-develop.qmd
    - 04-parent.qmd
    - 05-peer.qmd
    - 06-conclu.qmd
    - 07-references.qmd
  appendices:
    - 08-appendix.qmd
bibliography: Thesis.bib
lot: true
lof: true
include-before:
  - "\\textbf{Abstract}"
  - "This is the abstract."
  - "\\newpage\\textbf{Acknowledgements}"
  - "To be added."
format:
  pdf:
    documentclass: ut-thesis
    header-includes:
      - \widowpenalty10000
      - \clubpenalty10000
      - \pagenumbering{roman}
      - \usepackage{titleps}
      - \newpagestyle{mystyle}{\setfoot{}{\thepage}{}}
      - \pagestyle{mystyle}
      - \makeatletter
      - \def\ps@plain{\let\@mkboth\@gobbletwo\let\@oddhead\@empty\let\@evenhead\@empty\def\@oddfoot{\hfil\thepage\hfil}\def\@evenfoot{\hfil\thepage\hfil}}
      - \makeatother
      - \degree{Doctor of Philosophy in Political Science}
      - \gradyear{2024}
      - \department{Political Science}
