project:
  type: book
book:
  title: "Gendered Political Socialization"
  subtitle: "Why Women and Men Still Differ in Their Political Interests"
  author: "Alexandre Fortier-Chouinard"
  date: last-modified
  date-format: "MMMM D, YYYY"
  chapters:
    - index.qmd
    #- 01-intro.qmd
    - 02-method.qmd
    - 03-develop.qmd
    - 04-parent.qmd
    - 05-peer.qmd
    - 06-conclu.qmd
    - 07-references.qmd
  appendices:
    - 08-appendix.qmd
bibliography: Thesis.bib
toc: true
toc-depth: 5
lof: true
lot: true
linestretch: 1.5
abstract: "This is my abstract."
include-before: "Acknowledgements."
geometry:
  - top=20mm
  - left=32mm
  - right=20mm
  - bottom=20mm
  - heightrounded
header-includes:
  - \widowpenalty10000
  - \clubpenalty10000
format:
  pdf:
    documentclass: scrreprt
